definitions:
  main.User:
    properties:
      last_name:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/save:
    get:
      consumes:
      - application/json
      description: save sended user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: save user
swagger: "2.0"
